### ISSUE TITLE
Roadmap to SOGo 3

### ISSUE THREAD

**Issue by benjamindahl** [mattronix/sogo_ynh#1]
Are there any Plans to integrate SOGo 3 into Yuno Host?

cheers

Benny

**Comment by mattronix** [comment]
Not that I know of but my package will install sogo 3 on yunohost it will not upgrade sogo two to sogo three but I can help with that it's really easy :)
I might try and get it as an official package.
On Jun 16, 2016 2:09 PM, benjamindahl <notifications@github.com> wrote:Are there any Plans to integrate SOGo 3 into Yuno Host?

cheers

Benny

**Comment by benjamindahl** [comment]
I installed Your package and it installed SOGo 2. How does the upgrade process to SOGo 3 work? 

I also put your package on the wishlist for yunohost-apps.

![bildschirmfoto 2016-06-16 um 16 26 37](https://cloud.githubusercontent.com/assets/2698024/16120617/6078b6ce-33e0-11e6-9b64-438d58b62a18.png)
![bildschirmfoto 2016-06-16 um 16 26 45](https://cloud.githubusercontent.com/assets/2698024/16120618/6078ea9a-33e0-11e6-808d-9e41166051b3.png)
![bildschirmfoto 2016-06-16 um 16 27 14](https://cloud.githubusercontent.com/assets/2698024/16120620/607951a6-33e0-11e6-8db5-effc91572f39.png)
![bildschirmfoto 2016-06-16 um 16 27 28](https://cloud.githubusercontent.com/assets/2698024/16120619/60791ef2-33e0-11e6-8805-3d84467ec5b4.png)

**Comment by mattronix** [comment]
Hi Benjamin,


Not sure if i sent this already but to upgrade my sogo package to SOGO 3 you need to do the following:


apt-get remove sogo  

in /etc/apt/sources.list or /etc/aptsources.list.d/sogo.list 

find  "deb http://inverse.ca/debian <http://inverse.ca/debian>” and change it to  "deb http://inverse.ca/debian-v3 <http://inverse.ca/debian-v3>”

then do apt-get update

and apt-get install sogo 

This should work i have tested it a few times and it seems to work the database dose not need an upgrade and apt-get remove will not remove any data.
sogo 3 will pickup on the conf file in /etc/sogo/ and connect back to the old SQL database.

let me know if you have troubles or any questions :)

**Comment by benjamindahl** [comment]
Yeah, it works. Thanks.

I had to uninstall libsope1 additionally because of dependency-errors during installtion of sogo3. But finally it worked.

cheers.

Benny

**Comment by mattronix** [comment]
yes that happened to me in some cases but not all i will note that as well. 

as a default install libsope1. 

Thanks for reporting the issue let me know if i can help with anything else :)
